
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './header/page'
import { Providers } from './provider'
import Floater from '../Components/Floater'
import {ReduxProvider} from '../redux/provider'
import { useRouter } from 'next/navigation'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const fetchCache = "default-no-store"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

<html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
        <Providers>
        <Header/>
        <Floater/>
        {children}
        </Providers>
        </ReduxProvider>
      </body>
    </html>
  )
}
